<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Member;

class MemberSeeder extends Seeder
{
    public function run()
    {
        $names = [
            'Oliver Alampayan',
            'Agang Pajon',
            'Agang Cirilo',
            'Agang Edwin',
            'Agang Rolando',
            'Alampayan Pado',
            'Alampayan Junior Alma',
            'Alampayan Larry',
            'Alampayan Judito',
            'Aplacador Titing',
            'Aplacador Dylyn',
            'Aplacador Joaquin',
            'Aplacador Fernando',
            'Aplacador Febe Jr.',
            'Aplacador Vina',
            'Aplacador Dadang',
            'Alombrado Ester',
            'Amoncot Kish',
            'Ayunca Allan',
            'Aspirin Fedil',
            'Arcaya Lucresio',
            'Batistis Boy',
            'Batistis Louie',
            'Bona Ariel',
            'Cabilan Francis',
            'Buhayang Dondon',
            'Babao Nerio',
            'Cortejos Cristian',
            'Cortejos Orion',
            'Canales Andres',
            'Cubio Titing',
            'Corpuz Arturo',
            'Culaba Neil',
            'Cabilan Berto',
            'Cabilan Malbert',
            'Cosare Marino',
            'Calunia Carlo',
            'Calunia Boy',
            'Calunia Margie',
            'Calunia Victoria',
            'Victor Catalan',
            'Coscos Rico',
            'Cosgafa Bruno',
            'Cerejo John Arfe',
            'Cano Sally',
            'Cascas Lodie',
            'Cano Eboy',
            'Cano Samuel',
            'Cosap Ponciano',
            'Cosgafa Gemma',
            'Boja Junior',
            'Aduanza Nolzo',
            'Bulanon Jesrel',
            'Cereligia Rey',
            'Aguanza Heraldo',
            'De Vera Concordia',
            'Durango Rowena',
            'Dagohoy Sidro',
            'Dumadapat Allen',
            'Espina Vilma',
            'Enad Eric',
            'Gallo Sepen',
            'Gonzalos Lolong',
            'Gabi Ejoy',
            'Gutas Reneil',
            'Leyco Edsel',
            'Leyco Dado',
            'Lumictin Arsenio',
            'Lumictin Dado',
            'Lumictin Pacia',
            'Lumictin Harold',
            'Lumactod Cresencio Jr.',
            'Lumactod Jason',
            'Lumictin Petronilo Jr.',
            'Lumictin Jojo',
            'Lumactod Tane',
            'Lumictin Jrvin',
            'Jubahib Richie',
            'Morastel Romel',
            'Mante Jaime',
            'Mamon Jomarie',
            'Momongan Aladin',
            'Nabuya Marlon',
            'Nabuya Erning',
            'Nabuya Edok',
            'Omus Calpo',
            'Omus Larry',
            'Omus Nicasio Jr.',
            'Orzane Joward',
            'Ondoy Oliver',
            'Ondoy Julius',
            'Ondoy Meliton',
            'Patac Ponciano',
            'Patac Boboy - Marites',
            'Patac Babi',
            'Patolin Pablo',
            'Policios Fernando',
            'Polison Fredo',
            'Nina Iligan',
            'Compay Weng',
            'Polison Andy',
            'Polison Jason',
            'Policios Ricky',
            'Ramos Daday',
            'Rizaldo Joey',
            'Saavedra Jomar',
            'Savarez Dondon',
            'Sab Brigette',
            'Somogan Jonathan',
            'Sequiel Samuel',
            'Sarcole Caloy',
            'Sabang Eugen',
            'Sab Ciro',
            'Sab Meling',
            'Taquero Danny',
            'Vivo Titing',
            'Saligota Rochelle',
            'Tunga Jaime',
            'Nabuya Ai-Ai',
            'Nabuya Nelson',
            'Taghap Darwin',
            'Policios Junjun',
            'Vidal Reservo',
            'Omus Refer',
            'Lumictin Esmeraldo',
            'Lerin Joker',
            'Pangilinan Jonjon',
            'Terce Serio',
            'Cosare Lino',
            'Policios Rik-rik',
            'Odtuhan Utoy',
            'Tumabang Jeje',
            'Sab Malo-Ordo',
            'Alampayan Nino',
            'Rallos Randy',
            'Enocian Daniel',
            'Ocaraga Angelo',
            'Omus Jeffrey',
            'Nognay Gaga',
            'Robles Ojeng Jr.',
            'Moral Charlito',
            'Pacot Emely-Henry',
            'Omus Arman',
            'Compay Joward',
            'Leopardas Judy',
            'Lumictin Dandan',
            'Lumictin Merryjoy',
            'Vivo Menes',
            'Lorena Gab',
            'Sidro Polison',
            'Mejares Kevin',
            'Cabilan Lito',
            'Helon Loquiano',
            'Sering Panjan',
            'Marcha Jajanlangit',
            'Joseph Ojena',
            'Rizaldo Cerilo',
            'Joseph Corsiga',
            'Rolan Nabuya',
            'Mianic Buhayang',
            'Sab Belen Polot',
            'Sab Jolito',
            'Necidel Kevin Labastida',
            'Alojado Martin Kiara',
            'Jemboy Namoco',
            'Adtuhan Oding',
        ];

        foreach ($names as $name) {
            Member::firstOrCreate(['name' => $name]);
        }
    }
}
